apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-container
        image: "${REGISTRY}/frontend-service:${TAGS}"
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DATABASE_URL
          value: "mysql+pymysql://root:$(DB_PASSWORD)@mysql-service:3306/shoppingdb"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      # Removed volumeMounts related to Key Vault
      # Removed volume section as Key Vault volume is no longer used
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend-service
  ports:
    - port: 80
      targetPort: 5000

