# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- manual

variables:
  - group: environment-variables
  - group: key-vault

stages:
              
  - stage: Monitoring
    displayName: Monitoring
    pool:
        name: '$(vmImageName)'
        demands:
          - Agent.Name -equals $(AgentName)
    jobs:
      - job: InstallMonitoring
        displayName: "Install Prometheus & Grafana"
        pool:
         name: '$(vmImageName)'
         demands:
           - Agent.Name -equals $(AgentName)
        steps:
          
          - task: KubectlInstaller@0
            displayName: 'Kubectl Installer'
            inputs:
              kubectlVersion: 'latest'


          - task: replacetokens@6
            displayName: Replacing Variables in Manifest Files
            inputs:
              root: '$(System.DefaultWorkingDirectory)/k8s'
              sources: '**/*.yaml'
              tokenPattern: 'custom'
              tokenPrefix: '${'
              tokenSuffix: '}'


          - task: HelmInstaller@1
            displayName: "Installing Helm"
            inputs:
              helmVersionToInstall: 'latest'


          # - script: |
          #     helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          #     helm repo update
          #   displayName: 'Add ingress-nginx Helm repo'

          # - task: HelmDeploy@1
          #   displayName: 'Install NGINX Ingress Controller'
          #   inputs:
          #     connectionType: 'Azure Resource Manager'
          #     azureSubscription: 'Azure-Devops'
          #     azureResourceGroup: '$(ResourceGroup)'
          #     kubernetesCluster: 'Tanmaya-portfolio-aks-cluster'
          #     useClusterAdmin: true
          #     namespace: 'default'
          #     command: 'upgrade'
          #     chartType: 'Name'
          #     chartName: 'ingress-nginx/ingress-nginx'
          #     releaseName: 'nginx-ingress'
          #     overrideValues: 'controller.service.type=LoadBalancer'
          #     install: true


          - task: HelmDeploy@1
            displayName: "Install kube-prometheus-stack"
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Azure-Devops'
              azureResourceGroup: 'aks-rg'
              kubernetesCluster: 'Tanmaya-portfolio-aks-cluster'
              useClusterAdmin: true
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'prometheus-community/kube-prometheus-stack'
              releaseName: 'kind-prometheus'
              namespace: 'default'
              install: true
              arguments: >-
                --set prometheus.service.type=ClusterIP
                --set grafana.service.type=LoadBalancer
                --set grafana.adminPassword=$(grafana)
                --wait
              # --set grafana.ingress.enabled=false
              # --set grafana.env.GF_SERVER_ROOT_URL="/grafana"
              # --set prometheus.prometheusSpec.externalUrl="/prometheus"
                 
      
          # - task: KubernetesManifest@1
          #   inputs:
          #     action: 'deploy'
          #     connectionType: 'kubernetesServiceConnection'
          #     kubernetesServiceConnection: '$(ServiceConnectionAKS)'
          #     namespace: 'default'
          #     manifests: |
          #       $(System.DefaultWorkingDirectory)/k8s/monitoring-ingress.yaml

